void *objc_msgSend(void *obj, void *sel);
void *objc_msgSend0(void *obj, void *sel)                                                                                                       { return ((void * (*)(void *, void *))objc_msgSend)(obj, sel); }
void *objc_msgSend1(void *obj, void *sel, void *a1)                                                                                             { return ((void * (*)(void *, void *, void *))objc_msgSend)(obj, sel, a1); }
void *objc_msgSend2(void *obj, void *sel, void *a1, void *a2)                                                                                   { return ((void * (*)(void *, void *, void *, void *))objc_msgSend)(obj, sel, a1, a2); }
void *objc_msgSend3(void *obj, void *sel, void *a1, void *a2, void *a3)                                                                         { return ((void * (*)(void *, void *, void *, void *, void *))objc_msgSend)(obj, sel, a1, a2, a3); }
void *objc_msgSend4(void *obj, void *sel, void *a1, void *a2, void *a3, void *a4)                                                               { return ((void * (*)(void *, void *, void *, void *, void *, void *))objc_msgSend)(obj, sel, a1, a2, a3, a4); }
void *objc_msgSend5(void *obj, void *sel, void *a1, void *a2, void *a3, void *a4, void *a5)                                                     { return ((void * (*)(void *, void *, void *, void *, void *, void *, void *))objc_msgSend)(obj, sel, a1, a2, a3, a4, a5); }
void *objc_msgSend6(void *obj, void *sel, void *a1, void *a2, void *a3, void *a4, void *a5, void *a6)                                           { return ((void * (*)(void *, void *, void *, void *, void *, void *, void *, void *))objc_msgSend)(obj, sel, a1, a2, a3, a4, a5, a6); }
void *objc_msgSend7(void *obj, void *sel, void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7)                                 { return ((void * (*)(void *, void *, void *, void *, void *, void *, void *, void *, void *))objc_msgSend)(obj, sel, a1, a2, a3, a4, a5, a6, a7); }
void *objc_msgSend8(void *obj, void *sel, void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7, void *a8)                       { return ((void * (*)(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *))objc_msgSend)(obj, sel, a1, a2, a3, a4, a5, a6, a7, a8); }
void *objc_msgSend9(void *obj, void *sel, void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7, void *a8, void *a9)             { return ((void * (*)(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *))objc_msgSend)(obj, sel, a1, a2, a3, a4, a5, a6, a7, a8, a9); }
void *objc_msgSend10(void *obj, void *sel, void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7, void *a8, void *a9, void *a10) { return ((void * (*)(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *))objc_msgSend)(obj, sel, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10); }
